version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=postgres
    ports:
      - "5006:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app-network
  app:
    build: .
    depends_on:
      - db
    ports:
      - "5005:8080"
    networks:
      - app-network
networks:
  app-network:
volumes:
  db-data: